### PR TITLE
Add Ruby 2.4 to Travis CI

### PR DESCRIPTION
**Pull request by junaruga**
It's time to add Ruby 2.4 to Travis CI.

### CODE REVIEW

**Comment by junaruga** [comment]
Travis does not work?

**Comment by junaruga** [comment]
Travis is not active for this repo: https://travis-ci.org/cucumber/cucumber-ruby-wire

**Comment by mattwynne** [comment]
OK I think I enabled it now.

**Comment by junaruga** [comment]
@mattwynne thanks!

**Pull request merged**
