### PR TITLE
Fix ci

### PR DESCRIPTION
**Pull request by canmor**
### 🤔 What's changed?

Lock version of cucumber-core and aruba in Gemfile to fix broken dependencies an CI build

### ⚡️ What's your motivation? 

- :bank: Refactoring/debt/DX (improvement to code design, tooling, documentation etc. without changing behaviour)

This should not affect user, only affects development

### ♻️ Anything particular you want feedback on?

Maybe better to set CUCUMBER_USE_RELEASED_GEMS environment variable and leave dependencies version to gemspec, I do not have the background of this.

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

### CODE REVIEW

**Comment by mpkorstanje** [comment]
> Maybe better to set CUCUMBER_USE_RELEASED_GEMS environment variable and leave dependencies version to gemspec, I do not have the background of this.

Could you elaborate on this?

Note: I don't know much about Ruby best practices. I just tried to patch CI as well.

**Comment by canmor** [comment]
I don't know much about ruby best practices too, what I mean is when I look at the `Gemfile`, it provides statements to declare dependencies of `cucumber-core`, `cucumber` and `aruba`, while all of these dependencies are already declared by the `.gemspec` file.

```Gemfile
if ENV['CUCUMBER_RUBY_CORE']
  gem 'cucumber-core', path: ENV['CUCUMBER_RUBY_CORE']
elsif !ENV['CUCUMBER_USE_RELEASED_GEMS']
  gem 'cucumber-core', github: 'cucumber/cucumber-ruby-core', branch: 'main'
end

if ENV['CUCUMBER_RUBY']
  gem 'cucumber', path: ENV['CUCUMBER_RUBY']
elsif !ENV['CUCUMBER_USE_RELEASED_GEMS']
  gem 'cucumber', github: 'cucumber/cucumber-ruby', tag: 'v7.1.0'
end

gem 'aruba', github: 'cucumber/aruba', branch: 'main' # Waiting for a new release of aruba
```

Sometime people use this pattern by overwriting versions in `.gemspec` file to apply more relaxed version constraints for local development in the Gemfile specifies.

I guess that's why there's a ENV switch `CUCUMBER_USE_RELEASED_GEMS` here, this Gemfile used to point cucumber-ruby-core and `aruba` to HEAD version of main branch at development, setting CUCUMBER_USE_RELEASED_GEMS can leave version of `cucumber-core` and `cucumber` to declared by `.gemspec` (but aruba is not guarded by this ENV, it's weird).

Now, there are version conflict of dependencies if we keep referring to main branch of `aruba` and `cucumber-ruby-core`, since we still stuck at `cucumber` v7.1, main branch of `aruba` ask for `cucumber` > 8.

Either we lock versions of `cucumber-core` and `aruba` in Gemfile instead of pointing to developing main branch (one day we keep this repo up-to-date to cucumber, may be we could go back to this again),
or we can put all versions declaration in Gemfile under guard of `CUCUMBER_USE_RELEASED_GEMS`, then set CUCUMBER_USE_RELEASED_GEMS=1 while running CI test workflow, which means during test stage, we adopt the same dependencies as the Gem release.

To be clear, I don't have too much background about this project, all of this understands is my personal aspect.

**Comment by canmor** [comment]
Another way to solved this could be go straight to cucumber v8, v9, I have some tries on draft #67 , but I think that's could be a little bit big leap, we can at least reenable the pipeline of CI, make this project spin at first.

**Comment by mpkorstanje** [comment]
Thanks for the explanation!

I  do suspect the version override for Aruba might have to be pulled up into one of the if-else branches. But I'm happy to make CI pass and let you refine the solution in future iterations.

**Pull request merged**
